name: CI
on: [push, pull_request]

jobs:
  build:
    strategy:
      fail-fast: false
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: olafurpg/setup-scala@v10
      - name: Setup Scala Native environment
        run: |
            sudo apt-get update
            sudo apt install clang
      - name: Native link
        run: sbt nativeLink
      - name: Run
        run: ./target/scala-2.13/test-os-lib-on-native-out

